# filebeat.config:
#   modules:
#     path: ${path.config}/modules.d/*.yml
#     reload.enabled: false

processors:
  - drop_event:
      when:
        regexp:
          container.name: '.*(abc|def).*'

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.logstash:
  hosts: [ 'logstash01:5044' ]

# output.elasticsearch:
#   hosts: [ "http://es01:9200", "http://es02:9200", "http://es03:9200" ]