filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

output.elasticsearch:
  hosts: [ "http://es01:9200" ]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana01:5601"
